export const AUTH_LOCKOUT_THRESHOLD = 5;
export const AUTH_LOCKOUT_DURATION_MS = 15 * 60 * 1000;

export const AUTH_STANDARD_SESSION_MAX_AGE_SECONDS = 24 * 60 * 60;
export const AUTH_REMEMBER_SESSION_MAX_AGE_SECONDS = 30 * 24 * 60 * 60;

export const AUTH_PASSWORD_RESET_TOKEN_TTL_MS = 60 * 60 * 1000;
export const AUTH_PASSWORD_RESET_GENERIC_MESSAGE =
  "If that email exists, we sent a reset code with the next steps.";
export const AUTH_PASSWORD_RESET_SUCCESS_MESSAGE =
  "Your password has been updated. You can sign in now.";

export const AUTH_ERROR_CODES = {
  INVALID_IDENTIFIER: "AUTH_INVALID_IDENTIFIER",
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
  RESET_TOKEN_INVALID: "AUTH_RESET_TOKEN_INVALID",
  RESET_TOKEN_EXPIRED: "AUTH_RESET_TOKEN_EXPIRED",
  RESET_TOKEN_CONSUMED: "AUTH_RESET_TOKEN_CONSUMED",
} as const;
